### PR TITLE
Ft delete article endpoint 63

### PR DESCRIPTION
**Pull request by beblicarl**
#### Pre-Submission Checklist

-   [x ] Your pull request targets the `main` branch.
-   [x ] Branch name is descriptive and follows the guidelines [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices).
-   [x ] All tests pass . Use `git commit --amend` to amend any fixes.

#### Checklist:

-   [x] All tests are passing.
-   [x] Tested changes locally.
-   [x] Improved documentation or readme where necessary.
-   [x] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).

#### What does this PR do?

This pr provides the endpoint for deleting an article
#### How should this be manually tested?

1. Start the server with `npm start` 
2. Make a delete request to this URL `localhost:3000/api/v1/articles/<:articleId> ` 
3. This successfully returns `Article has successfully been deleted`
 

##### Any background context you want to provide?

This is an endpoint for the employee to be able to delete an article
#### What are the relevant issues?
This endpoint deletes articles using their id

#### Screenshots (if appropriate)

image

#### Does it require any deployments updates ?

https://github.com/tbf-challenge/teamwork-be/compare/ft-delete-article-endpoint-63?expand=1

### CODE REVIEW

**Comment by beblicarl** [comment]
Good morning @jocrah , hope you are good ?
Kindly review this branch for me

**Comment by beblicarl** [comment]
i just realised, though the code works, the message in the response body appears empty in postman @jocrah

**Comment by jocrah** [comment]
> i just realised, though the code works, the message in the response body appears empty in postman @jocrah

@beblicarl can you elaborate on code working but message being empty? can you share the response?

**Comment by beblicarl** [comment]
> > i just realised, though the code works, the message in the response body appears empty in postman @jocrah
> 
> @beblicarl can you elaborate on code working but message being empty? can you share the response?

1. When i make a DELETE request with an id the particular post with that id gets deleted. For this example i sent a delete request with an id of 10. However, on postman the response body remains empty as seen in the picture below. I also attached a screenshot of what gets printed out in VSCODE terminal anytime i make a DELETE request

image
image


2. To confirm whether the particular post with an id of 10 is deleted i make a GET request to get all posts and the post with the ID of 10 is visibily missing.

image

**Comment by jocrah** [comment]
@beblicarl, understood. Is the response you're returning according to the specifications in the product doc?

I think the reason for the no response is that you're using the correct status code usually used for deleting resources: `204 No Content`.  No matter what you return, no response is returned when you use that status code.  You can confirm by switching to `200` and seeing if you get your response.

I've never known this before your question though but suspected that might be the cause so searched a bit on that.

Screenshot 2022-08-19 at 12 23 12 PM

**Comment by beblicarl** [comment]
> @beblicarl, understood. Is the response you're returning according to the specifications in the product doc?
> 
> I think the reason for the no response is that you're using the correct status code usually used for deleting resources: `204 No Content`. No matter what you return, no response is returned when you use that status code. You can confirm by switching to `200` and seeing if you get your response.
> 
> I've never known this before your question though but suspected that might be the cause so searched a bit on that.
> 
> Screenshot 2022-08-19 at 12 23 12 PM

1. The response i am returning is according to the specifications in the product doc.
2. The 204 was used by me because i wanted to be sure of the status code for a DELETE request. When i goggled i saw both 200 and 204 but i decided on 204 and i got that as a result.
3. I just changed it to 200 and it worked perfectly. I have learned a lot chale... thanks so much
4. I am pushing my final changes for final review

**Review by jocrah — APPROVED** [review]

**Pull request merged**
