### PR TITLE
refactor(endpoint): refactored delete endpoint [Start #104]

### PR DESCRIPTION
**Pull request by beblicarl**
#### Pre-Submission Checklist

-   [x] Your pull request targets the `main` branch.
-   [x] Branch name is descriptive and follows the guidelines [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices).
-   [x] All tests pass . Use `git commit --amend` to amend any fixes.

#### Checklist:

-   [x] All tests are passing.
-   [x] Tested changes locally.
-   [x] Improved documentation or readme where necessary.
-   [x] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).

#### What does this PR do?
This PR refactors the delete article endpoint

#### How should this be manually tested?

1. Start the server with `npm run dev`
2. Make a DELETE request to this endpoint `http://localhost:3000/api/v1/articles/<article:id>`
3. This successfully returns the sample data below
```
{
    "status": "success",
    "data": {
        "message": "Article was successfully deleted"
    }
}
```
4. You will realize the logic is now in the services folder
#### What are the relevant issues?
The Delete Article Endpoint needed to be refactored

### CODE REVIEW

**Comment by beblicarl** [comment]
@jocrah , kindly review this too for me

**Comment by beblicarl** [comment]
@jocrah , i have pushed new changes now. Kindly review

**Review by jocrah — COMMENTED** [review]
It looks cool @beblicarl. this is purely curiosity. been wondering what happens when you make a request with a non existent id

Could you let me know?

**Comment by beblicarl** [comment]
> It looks cool @beblicarl. this is purely curiosity. been wondering what happens when you make a request with a non existent id
> 
> Could you let me know?

1. The message below is what we get when the id is nonexistent
```
{
    "status": "success",
    "data": {
        "message": "Article was successfully deleted"
    }
}
```

**Comment by jocrah** [comment]
cool, thanks @beblicarl

**Review by jocrah — APPROVED** [review]

**Pull request merged**
