### PR TITLE
added new column to track likes on a post

### PR DESCRIPTION
**Pull request by beblicarl**
#### Pre-Submission Checklist

-   [x] Your pull request targets the `main` branch.
-   [x] Branch name is descriptive and follows the guidelines [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices).
-   [x] All tests pass . Use `git commit --amend` to amend any fixes.

#### Checklist:

-   [x] All tests are passing.
-   [x] Tested changes locally.
-   [x] Improved documentation or readme where necessary.
-   [x] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).

#### What does this PR do?

This PR adds new column to track likes on a post

#### How should this be manually tested?

1. Start the server with `npm run dev`
2. In the terminal you will see the `likesCount `field being added to the posts table

#### What are the relevant issues?
we had to add new column to track likes on a post

### CODE REVIEW

**Comment by beblicarl** [comment]
@jocrah , i am resolving all error messages

**Comment by jocrah** [comment]
> @jocrah , i am resolving all error messages

which error messages?

**Comment by beblicarl** [comment]
> > @jocrah , i am resolving all error messages
> 
> which error messages?

every single test that uses `fixtures.post` , `article endpoint test`, `gif endpoint tests` and so on. Github action says all builds have failed

**Comment by jocrah** [comment]
okay

**Pull request closed without merging**
