### PR TITLE
enhance create article endpoint properties 79

### PR DESCRIPTION
**Pull request by beblicarl**
#### Pre-Submission Checklist

-   [x] Your pull request targets the `main` branch.
-   [x] Branch name is descriptive and follows the guidelines [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices).
-   [x] All tests pass . Use `git commit --amend` to amend any fixes.

#### Checklist:

-   [x] All tests are passing.
-   [x] Tested changes locally.
-   [x] Improved documentation or readme where necessary.
-   [x] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).

#### How should this be manually tested?

1. Start the server with `npm start`
2.  Make a POST request with the sample data below with this endpoint` http://localhost:3000/api/v1/articles`

```
{
"userId" : 4,
"title" : "Carl Bond",
"image" : "Bond girls",
"content" : "Aww Carl",
"published" : "true"
}
```
3. This successfully returns` Article successfully posted`
4. Sample response body below

```
{
    "status": "success",
    "data": {
        "message": "Article successfully posted",
        "articleId": 32,
        "userId": 4,
        "title": "Carl Bond",
        "image": "Bond girls",
        "article": "Aww Carl",
        "published": true,
        "createdOn": "2022-08-22T10:07:09.719Z"
    }
}

```

#### What are the relevant issues?
I had to rename the name of some properties to correspond with the assignment material (Teamwork Pdf)

### CODE REVIEW

**Comment by beblicarl** [comment]
my good friends @jocrah and @jakazzy , i have made some changes to the property names of the Create-Article-Endpoint. In the response body, however, I added the `image` though it is not explicitly added in the assignment material. Please tell me what you think

image

**Comment by jocrah** [comment]
> i have made some changes to the property names of the Create-Article-Endpoint. In the response body, however, I added the `image` though it is not explicitly added in the assignment material. Please tell me what you think

@beblicarl apologies for the delay. well noted. any reason you have it closed now?

**Comment by beblicarl** [comment]
> > i have made some changes to the property names of the Create-Article-Endpoint. In the response body, however, I added the `image` though it is not explicitly added in the assignment material. Please tell me what you think
> 
> @beblicarl apologies for the delay. well noted. any reason you have it closed now?

you had merged so many PR since i sent this one and it would have caused way too many conflicts so i decided to close this one and do it all over

**Comment by jocrah** [comment]
> you had merged so many PR since i sent this one and it would have caused way too many conflicts so i decided to close this one and do it all over

sounds good. anyway you have just 3 files which can have conflicts. want to know what `way too many` means :smile:

**Comment by beblicarl** [comment]
> > you had merged so many PR since i sent this one and it would have caused way too many conflicts so i decided to close this one and do it all over
> 
> sounds good. anyway you have just 3 files which can have conflicts. want to know what `way too many` means 😄

I just thought it would be easier this way

**Pull request closed without merging**
